{
gsub(/35=0/,"____Heartbeat_____");
gsub(/35=1/,"____TestRequest_____");
gsub(/35=2/,"____ResendRequest_____");
gsub(/35=3/,"____Reject_____");
gsub(/35=4/,"____SequenceReset_____");
gsub(/35=5/,"____Logout_____");
gsub(/35=6/,"____IOI_____");
gsub(/35=7/,"____Advertisement_____");
gsub(/35=8/,"____ExecutionReport_____");
gsub(/35=9/,"____OrderCancelReject_____");
gsub(/35=A/,"____Logon_____");
gsub(/35=B/,"____News_____");
gsub(/35=C/,"____Email_____");
gsub(/35=D/,"____NewOrderSingle_____");
gsub(/35=Q/,"____DontKnowTrade(DKT)_____");
gsub(/35=R/,"____QuoteRequest_____");
gsub(/35=S/,"____Quote_____");

print;
}
